server:
  port: 9000
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
 file: ./logs/kafka-service.log
 level:
  root: INFO
  org:
  springframework: DEBUG

topic:
 name: user

spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: hackathon.infy2020@gmail.com
spring.mail.password: Samrat@123
spring.mail.test-connection: true

spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.transport.protocol: tls
spring.mail.properties.mail.smtp.starttls.enable: true
spring.mail.properties.mail.smtp.starttls.required: true
spring.mail.properties.mail.smtp.connectiontimeout: 5000
spring.mail.properties.mail.smtp.timeout: 5000
spring.mail.properties.mail.smtp.writetimeout: 5000

