server:
  port: 9000
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
 file: ./logs/kafka-service.log
 level:
  root: INFO
  org:
  springframework: DEBUG

topic:
 name: 
  appreciation: appreciation
  feedback: feedback
  course: course
  task: task

spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: hackathon.infy2020@gmail.com
spring.mail.password: Samrat@123
spring.mail.test-connection: true

spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.transport.protocol: tls
spring.mail.properties.mail.smtp.starttls.enable: true
spring.mail.properties.mail.smtp.starttls.required: true
spring.mail.properties.mail.smtp.connectiontimeout: 5000
spring.mail.properties.mail.smtp.timeout: 5000
spring.mail.properties.mail.smtp.writetimeout: 5000

app.appreciation.receiver.email.body: email-appreciation-body.ftl
app.appreciation.receiver.email.subject: email-appreciation-subject.ftl
app.appreciation.provider.email.body: email-appreciation-provider-body.ftl
app.appreciation.provider.email.subject: email-appreciation-provider-subject.ftl

app.feedback.receiver.email.body: email-feedback-body.ftl
app.feedback.receiver.email.subject: email-feedback-subject.ftl
app.feedback.provider.email.body: email-feedback-provider-body.ftl
app.feedback.provider.email.subject: email-feedback-provider-subject.ftl

app.course.complete.email.body: email-course-body.ftl
app.course.complete.email.subject: email-course-subject.ftl

app.task.complete.email.body: email-task-complete-body.ftl
app.task.complete.email.subject: email-task-complete-subject.ftl
app.task.complete.ack.email.body: email-task-complete-ack-body.ftl
app.task.complete.ack.email.subject: email-task-complete-ack-subject.ftl

app.task.assign.email.body: email-task-assign-body.ftl
app.task.assign.email.subject: email-task-assign-subject.ftl
app.task.assign.ack.email.body: email-task-assign-ack-body.ftl
app.task.assign.ack.email.subject: email-task-assign-ack-subject.ftl
